import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Footer } from '@/components/Footer';
import Navbar from '@/components/Navbar';
import styles from '@/styles/Home.module.css';
import shoe from '../public/shoe.svg';
import {HomePage} from '../components/Home'
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function getServerSideProps() {
    let recents = await prisma.articles.findMany({
        where: {
            published: true,
        },
        orderBy: {
            created_at: 'asc'
        },
        take: 3
      })
    return {
      props: {
        recents: JSON.parse(JSON.stringify(recents, (key, value) =>
        typeof value === 'bigint'
            ? value.toString()
            : value // return everything else unchanged
    )),
      }
    };
  }

const inter = Inter({ subsets: ['latin'] });

export default function Home(recents=[]) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image src={shoe} />
        <HomePage recents={recents}/>
      </main>
    </>
  );
}
